### ISSUE TITLE
sumologic-content-Qualys 

### ISSUE THREAD

**Issue by heatguy1986** [SumoLogic/sumologic-content#106]
Within the qualys collection, specifically the Qualys_Config.cfg file, it asks for a qualysReportURL. What is the qualysReportURL supposed to be?

I can't seem to get this going without having the correct URL. Are there examples I can get?

**Comment by wjakelee** [comment]
Hello,

Apologies for the late response on this. We actually have an out of the box C2C collector for [Qualys VMDR](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source/). Please take a look at this option for collection Qualys moving forward.

Thank you!
