### ISSUE TITLE
logs to cloudwatch

### ISSUE THREAD

**Issue by ozbillwang** [SumoLogic/sumologic-content#53]
Thanks to write this feature to collect logs (https://github.com/SumoLogic/sumologic-content/blob/master/Amazon_Web_Services/RDS/Log-Collection/rds.py) 

I run it and get collected logs.

```
[postgresqldev error/postgresql.log.2018-10-15-05] 2018-10-15 05:12:07 UTC::@:[25035]:LOG:  parameter "shared_preload_libraries" cannot be changed without restarting the server
[postgresqldev error/postgresql.log.2018-10-15-05] 2018-10-15 05:16:34 UTC::@:[25038]:LOG:  checkpoint starting: time
```

But I didn't see the codes to write logs to cloudwatch, similar codes should be like this: 

```
logs = boto3.client('logs')

response = logs.put_log_events(
    logGroupName=LOG_GROUP,
    logStreamName=LOG_STREAM,
    logEvents=[
        {
            'timestamp': timestamp,
            'message': time.strftime('%Y-%m-%d %H:%M:%S')+'\tHello world, here is our first log message!'
        }
    ]
)
```

Is it the right way to add this in `rds.py` or the codes will be executed with other ways to put logs to cloudwatch?

Do you accept PR to enable this feature?

**Comment by kb18951452** [comment]
We appreciate PRs, If you have one, please submit it.

**Comment by ozbillwang** [comment]
@kb18951452 

I did it as a lambda function. The codes are changed a lot. Let me know if you need it to be copied here or not 

https://github.com/ozbillwang/tf_module_rds_logs2cloudwatch/blob/master/source/main.py

### Steps

* download state file from s3 bucket (<account_id>-rds-logs-state).
* If the s3 bucket is not exist, create it first, and enable versioning.
* If the state file is not exist, ignore it.
* check the state in state file and make sure only read new logs
* push the latest logs to cloudwatch (default log group is /aws/rds_logs, log stream is the database identifier)
* adjust sequence token when push the logs to cloudwatch
* write state to state file and upload to s3

### System environment variables are required:

* DB_INSTANCE_IDENTIFIER
* (optional) INITIAL_DAYS_TO_INGEST
* (optional) LOG_GROUP
* (optional) BUCKET_NAME

**Comment by ozbillwang** [comment]
cc @danreichert

**Comment by danreichert** [comment]
Hi @ozbillwang 

Currently, the Python script works the way it does by saving its state on the EC2 instance and then sending the logs directly from the API to Sumo. I have considered turning it into a Lambda function, but saving state is a tricky one to work with in a way that is easy to set up. S3 may be a good place for a state file. 

Ideally, the function won't save the logs to Cloudwatch to reduce cost, and it will send directly to Sumo. 

Thank you for working on this! It definitely helps, and I'll look into it.

**Comment by ozbillwang** [comment]
yes, this function is stateful, not stateless, so I need think a way to save the state, on s3, dynamodb, ssm, or other place. Finally I go with simple way to use s3 to save it. 

Our company's way is to export the logs to cloudwatch first, any applications on aws. Then will set subscription filter to forward to sumologic, or splunk or others, depend on these logs which need be audit (security request), analyse or archive only, etc.  Second, it will be convenient for us, if one day we need adjust the backend logs system. 

So I will not raise PR then, seems it is not suitable here.
