### ISSUE TITLE
LinkedIn Spam From Your Reps

### ISSUE THREAD

**Issue by dmuth** [SumoLogic/sumologic-content#77]
This is not a big in your software code, however it is a bug in your moral code: one of the more brazen spams I've seen in LinkedIn from one of your staff:

![image](https://user-images.githubusercontent.com/374060/66089906-222c0c80-e54f-11e9-8641-08efb6bfedc3.png)

My recommendation is that you patch this person to ensure that the behavior in question ceases.

Thank you.

**Comment by spchin** [comment]
Thanks for bringing this to our attention, we will follow up.

**Comment by mcgroarty** [comment]
Perhaps you need to reopen the issue? I've received spam from SumoLogic on my personal email despite never having signed up nor consented to receive such. The mails do pass SPF and DKIM for the sumologic.com domain.

To facilitate debugging, I've fed all mails to my usual spam script. This submits messages to a collection of spam blacklist services, often with wonderful results.

**Comment by mcgroarty** [comment]
<img width="730" alt="Screen Shot 2021-04-14 at 10 45 25 AM" src="https://user-images.githubusercontent.com/2642531/114756213-5caf6180-9d0f-11eb-8d22-b15c2eb7ef3e.png">
